version: '3.8'


services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  qdrant_data:
